# Generated by Django 3.1 on 2021-02-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('Difficulty', models.CharField(max_length=10)),
                ('Author', models.CharField(max_length=20)),
            ],
        ),
    ]
