# Generated by Django 3.1 on 2021-02-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='challenges',
        ),
    ]
