# Generated by Django 3.1.7 on 2021-03-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20210309_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='last_solved',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
